name: GitHub Actions Testing
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Codebase
        run: echo 'LINTING SCRIPT'
  # testing-library:
  #   runs-on: ubuntu-latest
  #   needs: lint
  #   steps:
  #     - name: Checkout codebase
  #       uses: actions/checkout@v3
  #     - name: Install dependencies
  #       run: |
  #         npm ci
  #       working-directory: ./frontend
  #     - name: Run Testing Library on frontend
  #       run: |
  #         npm run test
  #       working-directory: ./frontend
  cypress:
    runs-on: ubuntu-latest
    # Specific container to run Cypress
    # container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    needs: lint
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Build containers
        run: |
          docker-compose build
      - name: Run containers
        run: |
          docker-compose up -d
      - name: Show directory
        run: pwd
      - name: Show files
        run: ls -la
      - name: File Exploring
        working-directory: ./frontend
        run: |
          pwd
          ls -la
          cat package.json
      # - name: Cypress run
      #   uses: cypress-io/github-action@v5
      #   with:
      #     wait-on: "http://localhost:8080"
      #     browser: chrome
      #     working-directory: ./frontend
      #     build: docker-compose build
      #     start: docker-compose up -d
      - name: Stop and remove containers
        run: |
          docker-compose down