name: GitHub Actions Testing
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Codebase
        run: echo 'LINTING SCRIPT'
  # testing-library:
  #   runs-on: ubuntu-latest
  #   needs: lint
  #   steps:
  #     - name: Checkout codebase
  #       uses: actions/checkout@v3
  #     - name: Install dependencies
  #       run: |
  #         npm ci
  #       working-directory: ./frontend
  #     - name: Run Testing Library on frontend
  #       run: |
  #         npm run test
  #       working-directory: ./frontend
  cypress:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Change to 'frontend' directory
        run: cd ./frontend
      - name: Install dependencies
        run: npm install
      - name: Start server
        run: npm start
      - name: Run Cypress test suite
        run: npx run cypress
      #   uses: cypress-io/github-action@v4
      #   with:
      #     command: npx cypress run
      #     browser: chrome