name: GitHub Actions Testing
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Codebase
        run: echo 'LINTING SCRIPT'
  # testing-library:
  #   runs-on: ubuntu-latest
  #   needs: lint
  #   steps:
  #     - name: Checkout codebase
  #       uses: actions/checkout@v3
  #     - name: Install dependencies
  #       run: |
  #         npm ci
  #       working-directory: ./frontend
  #     - name: Run Testing Library on frontend
  #       run: |
  #         npm run test
  #       working-directory: ./frontend
  cypress:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Build app containers
        run: |
          docker-compose build
      - name: Run app containers
        run: |
          docker-compose up -d
      - name: Build Cypress container
        run: |
          docker build -f ./frontend/Dockerfile.cypress -t testapp-cypress:latest ./frontend
      - name: Connect Cypress container to existing network and run tests
        run: |
          docker run --rm --network=dev-net testapp-cypress
      - name: Stop and remove containers
        run: |
          docker-compose down